"""
F1 Quiz Bot - Question Bank
Each question is a dict:
{
    "question": str,          # poll question text (Telegram limit ~255 chars)
    "options": [str, ...],    # 2-10 options (Telegram limit ~100 chars each)
    "correct": int,           # index into options
    "explanation": str,       # shown after answering (Telegram limit ~200 chars)
    "category": str,          # "history" | "records" | "drivers" | "teams" | "meme" | "rules"
    "difficulty": str,        # "easy" | "medium" | "hard" -> controls points awarded
}

NOTE: F1 stats (records, current champions, team names) change every season.
This bank is accurate through the 2023-2024 seasons. Revisit periodically —
see the bottom of this file for how to add more questions.
"""

QUESTIONS = [
    # ---------------- HISTORY ----------------
    {
        "question": "Who won the very first Formula 1 World Championship (1950)?",
        "options": ["Juan Manuel Fangio", "Giuseppe Farina", "Alberto Ascari", "Stirling Moss"],
        "correct": 1,
        "explanation": "Giuseppe 'Nino' Farina won the inaugural 1950 title driving for Alfa Romeo.",
        "category": "history",
        "difficulty": "hard",
    },
    {
        "question": "Which driver has won the most F1 World Championships (7, alongside one other)?",
        "options": ["Ayrton Senna", "Alain Prost", "Michael Schumacher", "Niki Lauda"],
        "correct": 2,
        "explanation": "Michael Schumacher and Lewis Hamilton are tied with 7 titles each.",
        "category": "history",
        "difficulty": "easy",
    },
    {
        "question": "In which decade did the first Monaco Grand Prix (as part of the F1 championship) take place?",
        "options": ["1920s", "1930s", "1950s", "1960s"],
        "correct": 2,
        "explanation": "Monaco joined the F1 calendar in 1950, the championship's very first year.",
        "category": "history",
        "difficulty": "medium",
    },
    {
        "question": "Which team did Ayrton Senna famously drive for when he won his 3 world titles?",
        "options": ["Williams", "Ferrari", "McLaren", "Lotus"],
        "correct": 2,
        "explanation": "Senna won his titles (1988, 1990, 1991) with McLaren-Honda.",
        "category": "history",
        "difficulty": "easy",
    },
    {
        "question": "Who is the youngest World Champion in F1 history (as of 2024)?",
        "options": ["Max Verstappen", "Lewis Hamilton", "Sebastian Vettel", "Fernando Alonso"],
        "correct": 2,
        "explanation": "Sebastian Vettel won his first title in 2010 at 23 years old.",
        "category": "history",
        "difficulty": "medium",
    },
    {
        "question": "Which nation has produced the most F1 World Champions?",
        "options": ["Germany", "Brazil", "United Kingdom", "Italy"],
        "correct": 2,
        "explanation": "The UK leads with champions like Hamilton, Hill, Mansell, Stewart and more.",
        "category": "history",
        "difficulty": "medium",
    },
    {
        "question": "What year did Formula 1 introduce the current V6 turbo-hybrid power units?",
        "options": ["2010", "2012", "2014", "2017"],
        "correct": 2,
        "explanation": "The 1.6L V6 turbo-hybrid era began in the 2014 season.",
        "category": "history",
        "difficulty": "medium",
    },
    {
        "question": "Which driver won the closest-ever title fight, decided by just half a point in 1984?",
        "options": ["Niki Lauda", "Alain Prost", "Nelson Piquet", "Keke Rosberg"],
        "correct": 0,
        "explanation": "Niki Lauda beat teammate Alain Prost by half a point — the closest title margin ever.",
        "category": "history",
        "difficulty": "hard",
    },
    {
        "question": "Who was the first driver to win a Formula 1 World Championship for Ferrari?",
        "options": ["Juan Manuel Fangio", "Alberto Ascari", "Mike Hawthorn", "Phil Hill"],
        "correct": 1,
        "explanation": "Alberto Ascari won Ferrari's first drivers' titles in 1952 and 1953.",
        "category": "history",
        "difficulty": "hard",
    },
    {
        "question": "Which race has most often closed out the F1 season in recent years?",
        "options": ["Abu Dhabi GP", "Brazilian GP", "Japanese GP", "United States GP"],
        "correct": 0,
        "explanation": "The Abu Dhabi Grand Prix at Yas Marina has closed the calendar in most recent seasons.",
        "category": "history",
        "difficulty": "easy",
    },

    # ---------------- RECORDS ----------------
    {
        "question": "Who holds the record for most F1 race wins in history (as of 2024)?",
        "options": ["Michael Schumacher", "Lewis Hamilton", "Sebastian Vettel", "Max Verstappen"],
        "correct": 1,
        "explanation": "Lewis Hamilton passed Schumacher's tally and leads the all-time wins list.",
        "category": "records",
        "difficulty": "easy",
    },
    {
        "question": "Who holds the record for most pole positions in F1 history?",
        "options": ["Ayrton Senna", "Michael Schumacher", "Lewis Hamilton", "Max Verstappen"],
        "correct": 2,
        "explanation": "Lewis Hamilton holds the all-time pole record, surpassing Senna and Schumacher.",
        "category": "records",
        "difficulty": "medium",
    },
    {
        "question": "Which team has won the most Constructors' Championships?",
        "options": ["McLaren", "Williams", "Ferrari", "Mercedes"],
        "correct": 2,
        "explanation": "Ferrari leads all teams in Constructors' titles by a wide margin.",
        "category": "records",
        "difficulty": "easy",
    },
    {
        "question": "In 2023, which driver set the record for most consecutive race wins in a single season?",
        "options": ["Lewis Hamilton", "Sebastian Vettel", "Max Verstappen", "Michael Schumacher"],
        "correct": 2,
        "explanation": "Max Verstappen won 10 consecutive races in 2023, a new F1 record.",
        "category": "records",
        "difficulty": "easy",
    },
    {
        "question": "Which team won a record 21 of 22 races in the 2023 season?",
        "options": ["McLaren", "Mercedes", "Ferrari", "Red Bull Racing"],
        "correct": 3,
        "explanation": "Red Bull's 2023 campaign is the most dominant single-team season in F1 history.",
        "category": "records",
        "difficulty": "medium",
    },
    {
        "question": "Who is the oldest driver to win an F1 World Championship?",
        "options": ["Juan Manuel Fangio", "Nigel Mansell", "Alain Prost", "Niki Lauda"],
        "correct": 0,
        "explanation": "Fangio won his fifth title in 1957 at age 46, the oldest champion ever.",
        "category": "records",
        "difficulty": "hard",
    },
    {
        "question": "Which circuit has hosted the most F1 World Championship races?",
        "options": ["Silverstone", "Monza", "Monaco", "Spa-Francorchamps"],
        "correct": 1,
        "explanation": "Monza has hosted an F1 race in almost every season since 1950, the most of any circuit.",
        "category": "records",
        "difficulty": "hard",
    },

    # ---------------- DRIVERS ----------------
    {
        "question": "Which driver's nickname is 'The Iceman'?",
        "options": ["Sebastian Vettel", "Kimi Raikkonen", "Valtteri Bottas", "Nico Rosberg"],
        "correct": 1,
        "explanation": "Kimi Raikkonen earned 'The Iceman' tag for his cool, deadpan demeanor.",
        "category": "drivers",
        "difficulty": "easy",
    },
    {
        "question": "Which driver is the son of a former F1 driver and dominated the sport in the early 2020s?",
        "options": ["Lando Norris", "Max Verstappen", "Charles Leclerc", "George Russell"],
        "correct": 1,
        "explanation": "Max Verstappen, son of ex-F1 driver Jos Verstappen, dominated 2021-2023.",
        "category": "drivers",
        "difficulty": "easy",
    },
    {
        "question": "Which driver drove for Renault, McLaren, Ferrari, and Alpine across his long F1 career?",
        "options": ["Jenson Button", "Fernando Alonso", "Felipe Massa", "Mark Webber"],
        "correct": 1,
        "explanation": "Fernando Alonso has raced for many teams including Renault, McLaren, Ferrari and Alpine.",
        "category": "drivers",
        "difficulty": "medium",
    },
    {
        "question": "Who was on the receiving end of the 'Multi-21' team orders controversy with Sebastian Vettel in 2013?",
        "options": ["Daniel Ricciardo", "Mark Webber", "Rubens Barrichello", "David Coulthard"],
        "correct": 1,
        "explanation": "Vettel ignored a 'Multi-21' hold-position order and passed teammate Mark Webber in Malaysia 2013.",
        "category": "drivers",
        "difficulty": "hard",
    },
    {
        "question": "Which driver is nicknamed the 'Honey Badger'?",
        "options": ["Daniel Ricciardo", "Pierre Gasly", "Carlos Sainz", "Esteban Ocon"],
        "correct": 0,
        "explanation": "Daniel Ricciardo picked up 'Honey Badger' for his fearless driving style.",
        "category": "drivers",
        "difficulty": "medium",
    },
    {
        "question": "Who won the 2021 F1 title on the final lap of the final race in Abu Dhabi amid huge controversy?",
        "options": ["Lewis Hamilton", "Max Verstappen", "Valtteri Bottas", "Sergio Perez"],
        "correct": 1,
        "explanation": "Max Verstappen passed Hamilton on the last lap after a controversial late Safety Car restart.",
        "category": "drivers",
        "difficulty": "easy",
    },
    {
        "question": "Which F1 driver is the son of a Formula 1 legend and raced for Haas in the early 2020s?",
        "options": ["Mick Schumacher", "Nico Hulkenberg", "Kevin Magnussen", "Esteban Ocon"],
        "correct": 0,
        "explanation": "Mick Schumacher, son of Michael Schumacher, raced in F1 for Haas.",
        "category": "drivers",
        "difficulty": "medium",
    },

    # ---------------- TEAMS ----------------
    {
        "question": "Which team is based in Brackley, UK and dominated the hybrid era from 2014-2020?",
        "options": ["Red Bull Racing", "Mercedes-AMG Petronas", "Aston Martin", "Williams"],
        "correct": 1,
        "explanation": "Mercedes is headquartered in Brackley and won 8 straight Constructors' titles from 2014.",
        "category": "teams",
        "difficulty": "medium",
    },
    {
        "question": "Which energy-drink-backed team won 4 straight titles with Vettel (2010-13) and again from 2021?",
        "options": ["Red Bull Racing", "Renault", "Force India", "Toro Rosso"],
        "correct": 0,
        "explanation": "Red Bull Racing has been one of F1's most dominant forces across two separate eras.",
        "category": "teams",
        "difficulty": "easy",
    },
    {
        "question": "What is the oldest continuously competing team in F1?",
        "options": ["McLaren", "Williams", "Ferrari", "Alfa Romeo"],
        "correct": 2,
        "explanation": "Ferrari has competed in every F1 season since the championship began in 1950.",
        "category": "teams",
        "difficulty": "easy",
    },
    {
        "question": "Which team famously raced a 'six-wheeled' car (the P34) in the 1970s?",
        "options": ["Lotus", "Tyrrell", "Brabham", "March"],
        "correct": 1,
        "explanation": "The Tyrrell P34 ran with four small front wheels and even won a race in 1976.",
        "category": "teams",
        "difficulty": "hard",
    },
    {
        "question": "Which team's clever 'double diffuser' helped them dominate the start of the 2009 season?",
        "options": ["Red Bull", "McLaren", "Brawn GP", "Toyota"],
        "correct": 2,
        "explanation": "Brawn GP won both titles in their only F1 season, 2009, thanks in part to the double diffuser.",
        "category": "teams",
        "difficulty": "medium",
    },

    # ---------------- RULES / TECH ----------------
    {
        "question": "How many points does a driver get for winning a Grand Prix under the current system?",
        "options": ["20", "25", "30", "10"],
        "correct": 1,
        "explanation": "A race win is worth 25 points under the scoring system introduced in 2010.",
        "category": "rules",
        "difficulty": "easy",
    },
    {
        "question": "What is DRS in Formula 1?",
        "options": [
            "Drag Reduction System",
            "Downforce Regulation Standard",
            "Driver Radio System",
            "Dynamic Race Strategy",
        ],
        "correct": 0,
        "explanation": "DRS opens a flap on the rear wing to reduce drag and aid overtaking.",
        "category": "rules",
        "difficulty": "easy",
    },
    {
        "question": "How many of each power unit element is a driver typically allowed per season before a grid penalty?",
        "options": ["1", "2", "4", "6"],
        "correct": 2,
        "explanation": "Drivers are generally allowed 4 of each power unit element per season without penalty.",
        "category": "rules",
        "difficulty": "hard",
    },
    {
        "question": "What does 'parc ferme' regulate?",
        "options": [
            "Where fans can park",
            "Restrictions on car setup changes after qualifying",
            "Pit lane speed limits",
            "Tyre allocation",
        ],
        "correct": 1,
        "explanation": "Parc fermé rules lock in most car setup parameters between qualifying and the race.",
        "category": "rules",
        "difficulty": "medium",
    },
    {
        "question": "What is the minimum weight limit for a current F1 car (with driver, without fuel), roughly?",
        "options": ["~600 kg", "~798 kg", "~900 kg", "~1050 kg"],
        "correct": 1,
        "explanation": "The 2024 minimum weight limit is 798 kg, up significantly due to hybrid components.",
        "category": "rules",
        "difficulty": "hard",
    },
    {
        "question": "What color flag indicates a session has been stopped?",
        "options": ["Yellow", "Blue", "Red", "Black and white"],
        "correct": 2,
        "explanation": "A red flag halts the session immediately, usually for a serious incident or unsafe conditions.",
        "category": "rules",
        "difficulty": "easy",
    },
    {
        "question": "What does a black flag with an orange circle mean?",
        "options": [
            "Mechanical problem, must pit",
            "Race is finished",
            "Overtaking allowed everywhere",
            "Track is wet",
        ],
        "correct": 0,
        "explanation": "The black-and-orange 'meatball' flag tells a driver their car has a mechanical issue and to pit.",
        "category": "rules",
        "difficulty": "medium",
    },

    # ---------------- MEME / ICONIC MOMENTS ----------------
    {
        "question": "\"Bwoah\" is a catchphrase most associated with which F1 personality?",
        "options": ["Kimi Raikkonen", "Nico Rosberg", "David Croft", "Toto Wolff"],
        "correct": 1,
        "explanation": "Nico Rosberg's exaggerated 'bwoah' became a widely-memed F1 sound bite.",
        "category": "meme",
        "difficulty": "medium",
    },
    {
        "question": "Which team was involved in the infamous 'Crashgate' scandal at the 2008 Singapore GP?",
        "options": ["McLaren", "Renault", "Ferrari", "BMW Sauber"],
        "correct": 1,
        "explanation": "Renault's Nelson Piquet Jr. deliberately crashed to help teammate Fernando Alonso win.",
        "category": "meme",
        "difficulty": "medium",
    },
    {
        "question": "\"Leave me alone, I know what I'm doing\" is a famous radio message from which driver?",
        "options": ["Kimi Raikkonen", "Sebastian Vettel", "Lewis Hamilton", "Max Verstappen"],
        "correct": 0,
        "explanation": "Kimi Raikkonen's blunt radio messages are legendary, this one from the 2012 Abu Dhabi GP.",
        "category": "meme",
        "difficulty": "easy",
    },
    {
        "question": "Which team principal's unbuttoned, untucked shirt became a running fan meme?",
        "options": ["Christian Horner", "Toto Wolff", "Guenther Steiner", "Zak Brown"],
        "correct": 1,
        "explanation": "Toto Wolff's shirt style is a well-known running joke among F1 fans.",
        "category": "meme",
        "difficulty": "medium",
    },
    {
        "question": "Which team's colorful, blunt team principal became a breakout star of 'Drive to Survive'?",
        "options": ["Guenther Steiner (Haas)", "Otmar Szafnauer", "Franz Tost", "Andreas Seidl"],
        "correct": 0,
        "explanation": "Guenther Steiner's fiery quotes on Drive to Survive made him a fan-favorite meme figure.",
        "category": "meme",
        "difficulty": "easy",
    },
    {
        "question": "The 2021 Silverstone Copse corner lap-1 crash famously involved Verstappen and which other driver?",
        "options": ["Sergio Perez", "Lewis Hamilton", "Charles Leclerc", "Lando Norris"],
        "correct": 1,
        "explanation": "Hamilton and Verstappen collided at Copse on lap 1 of the 2021 British GP.",
        "category": "meme",
        "difficulty": "easy",
    },
    {
        "question": "Which driver earned a reputation as F1's tyre-management 'smooth operator', nicknamed 'Minister of Defense'?",
        "options": ["Sergio Perez", "Lance Stroll", "Nico Hulkenberg", "Yuki Tsunoda"],
        "correct": 0,
        "explanation": "Sergio Perez earned the 'Minister of Defense' reputation for late-race tyre management and defending.",
        "category": "meme",
        "difficulty": "hard",
    },
    {
        "question": "Which chaotic, rain-soaked 2008 race saw Sebastian Vettel score Toro Rosso's only ever win?",
        "options": ["Monaco GP", "Italian GP", "Brazilian GP", "British GP"],
        "correct": 1,
        "explanation": "The 2008 Italian GP at Monza saw torrential rain and Sebastian Vettel's shock maiden win.",
        "category": "meme",
        "difficulty": "medium",
    },
    {
        "question": "Which team's iconic radio call 'Fernando is faster than you' became one of F1's biggest memes (2010)?",
        "options": ["Red Bull", "McLaren", "Ferrari", "Mercedes"],
        "correct": 1,
        "explanation": "McLaren's 2010 German GP call about Alonso became one of F1's all-time meme moments.",
        "category": "meme",
        "difficulty": "medium",
    },
    {
        "question": "In wet 2021 Turkish GP conditions, which rookie driver comically slid into the back of the Safety Car?",
        "options": ["Nikita Mazepin", "Mick Schumacher", "Antonio Giovinazzi", "George Russell"],
        "correct": 2,
        "explanation": "Antonio Giovinazzi famously crashed into the Safety Car itself in slippery conditions.",
        "category": "meme",
        "difficulty": "hard",
    },

    # ---------------- HISTORY (batch 2) ----------------
    {
        "question": "In which year was the Constructors' World Championship first introduced, won by Vanwall?",
        "options": ["1955", "1958", "1962", "1965"],
        "correct": 1,
        "explanation": "The Constructors' Championship began in 1958; Vanwall won the inaugural title.",
        "category": "history", "difficulty": "hard",
    },
    {
        "question": "Jim Clark won his two World Championships (1963, 1965) driving for which team?",
        "options": ["Lotus", "BRM", "Cooper", "Brabham"],
        "correct": 0,
        "explanation": "Jim Clark's titles came with Team Lotus under Colin Chapman.",
        "category": "history", "difficulty": "medium",
    },
    {
        "question": "Jackie Stewart won 3 World Championships in the late 1960s/early 1970s mainly with which team?",
        "options": ["Tyrrell", "McLaren", "Ferrari", "Lotus"],
        "correct": 0,
        "explanation": "Stewart won titles in 1969, 1971 and 1973, the latter two with Tyrrell.",
        "category": "history", "difficulty": "medium",
    },
    {
        "question": "Which manufacturer introduced the first turbocharged engine to F1, in 1977?",
        "options": ["Ferrari", "Renault", "BMW", "Honda"],
        "correct": 1,
        "explanation": "Renault's RS01 introduced turbo power to F1 in 1977, kicking off the turbo era.",
        "category": "history", "difficulty": "hard",
    },
    {
        "question": "Nelson Piquet won 3 World Championships, driving for Brabham and which other team?",
        "options": ["Williams", "McLaren", "Ferrari", "Lotus"],
        "correct": 0,
        "explanation": "Piquet won 1981 and 1983 with Brabham, then 1987 with Williams.",
        "category": "history", "difficulty": "medium",
    },
    {
        "question": "Damon Hill's 1996 title made him and his father the only father-son pair to both win F1 titles. Who was his father?",
        "options": ["Phil Hill", "Graham Hill", "Innes Ireland", "Jim Hill"],
        "correct": 1,
        "explanation": "Graham Hill won titles in 1962 and 1968; son Damon won in 1996, both with Williams-linked or Lotus/Williams teams.",
        "category": "history", "difficulty": "medium",
    },
    {
        "question": "Mika Hakkinen won back-to-back titles in 1998 and 1999 with which team?",
        "options": ["Williams", "McLaren", "Ferrari", "Jordan"],
        "correct": 1,
        "explanation": "Hakkinen's two titles came with McLaren-Mercedes.",
        "category": "history", "difficulty": "easy",
    },
    {
        "question": "In which year did F1 switch to the current 25-18-15-12-10-8-6-4-2-1 points system?",
        "options": ["2003", "2010", "2014", "2019"],
        "correct": 1,
        "explanation": "The current top-10 points structure was introduced in 2010.",
        "category": "history", "difficulty": "medium",
    },
    {
        "question": "Lewis Hamilton made history in 2007 as the first driver of which background to race full-time in F1?",
        "options": ["The first Black driver", "The first female driver", "The first Asian driver", "The first South American rookie"],
        "correct": 0,
        "explanation": "Hamilton's 2007 McLaren debut made him F1's first Black driver.",
        "category": "history", "difficulty": "easy",
    },
    {
        "question": "Which team dominated the early-to-mid 1990s, winning titles with Nigel Mansell (1992), Alain Prost (1993), and Damon Hill-era success?",
        "options": ["Williams", "Benetton", "Ferrari", "McLaren"],
        "correct": 0,
        "explanation": "Williams-Renault was the dominant force of the early 1990s.",
        "category": "history", "difficulty": "medium",
    },

    # ---------------- RECORDS (batch 2) ----------------
    {
        "question": "Which constructor has the most race wins in F1 history?",
        "options": ["McLaren", "Mercedes", "Ferrari", "Red Bull"],
        "correct": 2,
        "explanation": "Ferrari's decades of competing give it the most wins of any constructor.",
        "category": "records", "difficulty": "easy",
    },
    {
        "question": "Which circuit on the current F1 calendar is the longest lap?",
        "options": ["Monza", "Silverstone", "Spa-Francorchamps", "Suzuka"],
        "correct": 2,
        "explanation": "Spa-Francorchamps, at just over 7 km, is the longest lap on the current calendar.",
        "category": "records", "difficulty": "medium",
    },
    {
        "question": "Which circuit on the current calendar has one of the shortest laps?",
        "options": ["Monaco", "Baku", "Zandvoort", "Mexico City"],
        "correct": 0,
        "explanation": "Monaco's tight street circuit is one of the shortest laps on the calendar, at around 3.3 km.",
        "category": "records", "difficulty": "medium",
    },
    {
        "question": "Who became F1's youngest ever race starter, debuting at age 17 for Toro Rosso in 2015?",
        "options": ["Lando Norris", "Max Verstappen", "Charles Leclerc", "Lance Stroll"],
        "correct": 1,
        "explanation": "Max Verstappen debuted at the 2015 Australian GP aged just 17.",
        "category": "records", "difficulty": "easy",
    },
    {
        "question": "Who holds the record for most Grand Prix starts of any driver in F1 history (as of the mid-2020s)?",
        "options": ["Kimi Raikkonen", "Fernando Alonso", "Rubens Barrichello", "Michael Schumacher"],
        "correct": 1,
        "explanation": "Fernando Alonso's longevity saw him surpass Kimi Raikkonen's previous record for most starts.",
        "category": "records", "difficulty": "medium",
    },
    {
        "question": "Which driver is widely credited with the most 'Grand Slams' (pole, win, fastest lap, leading every lap) in a single race, in the 1960s?",
        "options": ["Jim Clark", "Jackie Stewart", "Graham Hill", "Juan Manuel Fangio"],
        "correct": 0,
        "explanation": "Jim Clark's dominance in the Lotus 25/33 produced more Grand Slams than any other driver.",
        "category": "records", "difficulty": "hard",
    },

    # ---------------- DRIVERS (batch 2) ----------------
    {
        "question": "Jenson Button won his only World Championship in 2009 with which team?",
        "options": ["McLaren", "Brawn GP", "Williams", "BAR"],
        "correct": 1,
        "explanation": "Button won the title in Brawn GP's sole, championship-winning season.",
        "category": "drivers", "difficulty": "easy",
    },
    {
        "question": "Alain Prost's calculating, smooth driving style earned him which nickname?",
        "options": ["The Professor", "The Iceman", "The Shark", "The Rain Master"],
        "correct": 0,
        "explanation": "Alain Prost was known as 'The Professor' for his tactical, precise approach to racing.",
        "category": "drivers", "difficulty": "easy",
    },
    {
        "question": "Niki Lauda suffered a near-fatal fiery crash at which circuit in 1976, then returned to racing weeks later?",
        "options": ["Monza", "Nurburgring", "Silverstone", "Zandvoort"],
        "correct": 1,
        "explanation": "Lauda's crash at the old Nürburgring Nordschleife in 1976 nearly killed him; he returned just 6 weeks later.",
        "category": "drivers", "difficulty": "medium",
    },
    {
        "question": "Ayrton Senna died in an accident during the 1994 San Marino Grand Prix at which circuit?",
        "options": ["Imola", "Monza", "Estoril", "Jerez"],
        "correct": 0,
        "explanation": "Senna's fatal accident occurred at Imola's Tamburello corner in May 1994.",
        "category": "drivers", "difficulty": "medium",
    },
    {
        "question": "Carlos Sainz's father, Carlos Sainz Sr., was a champion in which other motorsport discipline?",
        "options": ["Rallying (WRC)", "MotoGP", "IndyCar", "Le Mans endurance racing"],
        "correct": 0,
        "explanation": "Carlos Sainz Sr. is a two-time World Rally Champion and Dakar Rally winner.",
        "category": "drivers", "difficulty": "medium",
    },
    {
        "question": "Max Verstappen became F1's youngest ever race winner in 2016, on his debut for which team?",
        "options": ["Toro Rosso", "Red Bull Racing", "Renault", "Force India"],
        "correct": 1,
        "explanation": "Verstappen won the 2016 Spanish GP on his very first race for Red Bull Racing, aged 18.",
        "category": "drivers", "difficulty": "easy",
    },
    {
        "question": "Valtteri Bottas partnered Lewis Hamilton at Mercedes for how many seasons (2017-2021)?",
        "options": ["3", "4", "5", "6"],
        "correct": 2,
        "explanation": "Bottas was Hamilton's Mercedes teammate for five seasons before moving to Alfa Romeo.",
        "category": "drivers", "difficulty": "hard",
    },
    {
        "question": "Which future McLaren driver was at the center of a public 2022 contract dispute after Alpine announced him as their driver without his agreement?",
        "options": ["Esteban Ocon", "Oscar Piastri", "Pierre Gasly", "Lando Norris"],
        "correct": 1,
        "explanation": "Oscar Piastri publicly denied signing for Alpine in 2022 before it was confirmed he'd join McLaren instead.",
        "category": "meme", "difficulty": "medium",
    },

    # ---------------- TEAMS (batch 2) ----------------
    {
        "question": "Which current F1 team was previously known as Force India and then Racing Point?",
        "options": ["Alpine", "Aston Martin", "Williams", "Haas"],
        "correct": 1,
        "explanation": "The team went Jordan → Midland → Spyker → Force India → Racing Point → Aston Martin.",
        "category": "teams", "difficulty": "medium",
    },
    {
        "question": "Red Bull's junior team, Toro Rosso, was rebranded to which name in 2020?",
        "options": ["AlphaTauri", "RB", "Visa Cash App", "Scuderia AlphaTauri Honda"],
        "correct": 0,
        "explanation": "Toro Rosso became AlphaTauri from the 2020 season, later renamed again to RB in 2024.",
        "category": "teams", "difficulty": "medium",
    },
    {
        "question": "Which Swiss-based team has raced under names including Sauber, BMW Sauber, and Alfa Romeo?",
        "options": ["Sauber", "Minardi", "Arrows", "Jordan"],
        "correct": 0,
        "explanation": "The Hinwil, Switzerland-based team has rebranded multiple times while racing continuously since 1993.",
        "category": "teams", "difficulty": "medium",
    },
    {
        "question": "The original Team Lotus, under founder Colin Chapman, won multiple Constructors' titles between 1963 and 1978. How many?",
        "options": ["3", "5", "7", "9"],
        "correct": 2,
        "explanation": "Team Lotus won 7 Constructors' Championships in that innovative period under Colin Chapman.",
        "category": "teams", "difficulty": "hard",
    },
    {
        "question": "Jordan Grand Prix famously scored a surprise 1-2 finish at which 1998 race?",
        "options": ["Belgian GP", "Italian GP", "Monaco GP", "British GP"],
        "correct": 0,
        "explanation": "A chaotic, rain-hit 1998 Belgian GP at Spa saw Jordan claim its first ever win with a 1-2 finish.",
        "category": "teams", "difficulty": "hard",
    },
    {
        "question": "Which small Italian team was famous for giving future stars like Fernando Alonso their F1 debut, despite rarely scoring points?",
        "options": ["Minardi", "Arrows", "Forti", "Larrousse"],
        "correct": 0,
        "explanation": "Minardi was a beloved backmarker team and a launchpad for several future champions.",
        "category": "teams", "difficulty": "medium",
    },

    # ---------------- RULES (batch 2) ----------------
    {
        "question": "In what year were shorter Saturday 'Sprint' races introduced to the F1 calendar?",
        "options": ["2019", "2021", "2022", "2023"],
        "correct": 1,
        "explanation": "The Sprint format debuted at the 2021 British Grand Prix.",
        "category": "rules", "difficulty": "medium",
    },
    {
        "question": "What financial regulation, introduced in 2021, caps how much teams can spend developing their cars each season?",
        "options": ["The cost cap", "The budget ceiling", "The spending floor", "The fiscal limit"],
        "correct": 0,
        "explanation": "The cost cap restricts most team spending to try to level the competitive playing field.",
        "category": "rules", "difficulty": "medium",
    },
    {
        "question": "Since 2019, the point for fastest lap is only awarded if the driver also finishes where?",
        "options": ["In the top 5", "In the top 10", "On the podium", "In any position"],
        "correct": 1,
        "explanation": "The fastest-lap point only counts if that driver finishes in the top 10.",
        "category": "rules", "difficulty": "medium",
    },
    {
        "question": "What do waved yellow flags signal to drivers on track?",
        "options": [
            "A hazard ahead — no overtaking in that sector",
            "The race has finished",
            "Free practice has started",
            "Push as hard as possible",
        ],
        "correct": 0,
        "explanation": "Yellow flags warn of danger and prohibit overtaking until the hazard is passed.",
        "category": "rules", "difficulty": "easy",
    },
    {
        "question": "How is F1 qualifying structured into sessions?",
        "options": [
            "Q1, Q2, Q3, with the slowest cars eliminated after each",
            "A single 60-minute open session",
            "Two 30-minute sessions with no eliminations",
            "One lap per driver, fastest overall wins pole",
        ],
        "correct": 0,
        "explanation": "Modern qualifying knocks out the slowest cars after Q1 and Q2, leaving the top 10 to fight for pole in Q3.",
        "category": "rules", "difficulty": "easy",
    },
    {
        "question": "What is enforced in the pit lane at every circuit, for the safety of mechanics and crew?",
        "options": ["A minimum tyre pressure", "A pit lane speed limit", "A mandatory pit stop duration", "A ban on radio communication"],
        "correct": 1,
        "explanation": "Every circuit enforces a pit lane speed limit (commonly 60-80 km/h) for crew safety.",
        "category": "rules", "difficulty": "easy",
    },

    # ---------------- MEME / ICONIC (batch 2) ----------------
    {
        "question": "\"It's lights out and away we go!\" is a famous phrase associated with what moment in an F1 broadcast?",
        "options": ["The race start", "The podium ceremony", "Qualifying results", "The chequered flag"],
        "correct": 0,
        "explanation": "The phrase is used the instant the starting lights go out and the race begins.",
        "category": "meme", "difficulty": "easy",
    },
    {
        "question": "The controversial ending of which race led to a major review and reshuffle of FIA race direction?",
        "options": ["2021 Abu Dhabi GP", "2020 Turkish GP", "2019 German GP", "2018 German GP"],
        "correct": 0,
        "explanation": "The chaotic 2021 Abu Dhabi finale prompted the FIA to restructure how race control operates.",
        "category": "meme", "difficulty": "easy",
    },
    {
        "question": "Hamilton and Rosberg's Mercedes teammates famously collided out of the race at which 2016 Grand Prix?",
        "options": ["Spanish GP", "Austrian GP", "Belgian GP", "Japanese GP"],
        "correct": 0,
        "explanation": "Both Mercedes drivers crashed out of the 2016 Spanish GP after colliding on lap 1.",
        "category": "meme", "difficulty": "medium",
    },
    {
        "question": "Which driver earned the nickname 'Torpedo' after a string of collisions with other cars?",
        "options": ["Daniil Kvyat", "Pastor Maldonado", "Romain Grosjean", "Kevin Magnussen"],
        "correct": 0,
        "explanation": "Daniil Kvyat picked up the 'Torpedo' nickname after several high-profile clashes.",
        "category": "meme", "difficulty": "hard",
    },
    {
        "question": "Which driver survived a horrifying, fiery crash at the 2020 Bahrain GP, escaping the barrier within seconds?",
        "options": ["Romain Grosjean", "Nicholas Latifi", "Antonio Giovinazzi", "Daniil Kvyat"],
        "correct": 0,
        "explanation": "Romain Grosjean's car split in half and caught fire; he escaped in under 30 seconds, an incident credited with proving the halo device's value.",
        "category": "meme", "difficulty": "medium",
    },
    {
        "question": "Which Netflix docuseries is widely credited with significantly growing F1's US fanbase from 2019 onward?",
        "options": ["Drive to Survive", "Formula: The Documentary", "Grid Life", "Full Throttle"],
        "correct": 0,
        "explanation": "'Drive to Survive' introduced millions of new fans to F1's drivers and team drama.",
        "category": "meme", "difficulty": "easy",
    },
    {
        "question": "What is the traditional celebration performed by the top 3 finishers on the podium?",
        "options": ["Spraying champagne", "Cutting a cake", "Releasing doves", "Lighting fireworks"],
        "correct": 0,
        "explanation": "Champagne-spraying has been a podium tradition since the 1960s.",
        "category": "meme", "difficulty": "easy",
    },
    {
        "question": "The dry, deadpan phrase \"To be honest with you...\" repeated in interviews became a meme associated with which driver?",
        "options": ["George Russell", "Lando Norris", "Max Verstappen", "Lance Stroll"],
        "correct": 1,
        "explanation": "Lando Norris's frequent 'to be honest with you' opener became a fan-noted verbal tic.",
        "category": "meme", "difficulty": "medium",
    },

    # ---------------- HISTORY (batch 3) ----------------
    {
        "question": "In what year did Enzo Ferrari found Scuderia Ferrari, initially as a racing team rather than a manufacturer?",
        "options": ["1929", "1939", "1947", "1950"],
        "correct": 0,
        "explanation": "Scuderia Ferrari began in 1929 running other manufacturers' cars, before Ferrari built its own from 1947.",
        "category": "history", "difficulty": "hard",
    },
    {
        "question": "The 1976 title battle between Niki Lauda and James Hunt was dramatized in which 2013 film?",
        "options": ["Rush", "Senna", "Ford v Ferrari", "Le Mans"],
        "correct": 0,
        "explanation": "Ron Howard's 'Rush' depicted the intense 1976 Lauda-Hunt championship fight.",
        "category": "history", "difficulty": "easy",
    },
    {
        "question": "The 1994 season was marked by tragedy when which two drivers died in accidents at Imola on the same weekend?",
        "options": [
            "Ayrton Senna and Roland Ratzenberger",
            "Ayrton Senna and Gerhard Berger",
            "Roland Ratzenberger and Rubens Barrichello",
            "Ayrton Senna and Karl Wendlinger",
        ],
        "correct": 0,
        "explanation": "Roland Ratzenberger died in qualifying, and Ayrton Senna died in the race the next day.",
        "category": "history", "difficulty": "medium",
    },
    {
        "question": "Michael Schumacher won five consecutive World Championships with Ferrari across which span of years?",
        "options": ["1996-2000", "2000-2004", "1999-2003", "2001-2005"],
        "correct": 1,
        "explanation": "Schumacher's dominant Ferrari run produced titles every year from 2000 through 2004.",
        "category": "history", "difficulty": "medium",
    },
    {
        "question": "Which media company purchased Formula 1's commercial rights from Bernie Ecclestone's organization in 2017?",
        "options": ["Liberty Media", "Disney", "Comcast", "News Corp"],
        "correct": 0,
        "explanation": "Liberty Media acquired F1 in 2017, ending Bernie Ecclestone's decades running the sport commercially.",
        "category": "history", "difficulty": "medium",
    },
    {
        "question": "The chaotic 1982 season saw 11 different race winners. Who won that year's title despite winning only one race?",
        "options": ["Keke Rosberg", "Niki Lauda", "Alain Prost", "John Watson"],
        "correct": 0,
        "explanation": "Keke Rosberg won the 1982 title for Williams with consistency rather than dominance.",
        "category": "history", "difficulty": "hard",
    },
    {
        "question": "Juan Pablo Montoya had a fierce on-track rivalry with Michael Schumacher in the early 2000s while driving for which team?",
        "options": ["Williams", "McLaren", "Jordan", "BAR"],
        "correct": 0,
        "explanation": "Montoya's aggressive Williams drives often put him wheel-to-wheel with Schumacher's Ferrari.",
        "category": "history", "difficulty": "medium",
    },

    # ---------------- RECORDS (batch 3) ----------------
    {
        "question": "Nico Rosberg made headlines by doing what almost immediately after finally winning his first World Championship in 2016?",
        "options": [
            "Retiring from F1",
            "Signing a lifetime Mercedes contract",
            "Moving to Ferrari",
            "Announcing a return to karting",
        ],
        "correct": 0,
        "explanation": "Rosberg shocked the paddock by retiring just days after clinching the 2016 title.",
        "category": "records", "difficulty": "easy",
    },
    {
        "question": "Which team holds the record for most consecutive Constructors' Championships, winning 8 in a row from 2014-2021?",
        "options": ["Ferrari", "McLaren", "Mercedes", "Red Bull"],
        "correct": 2,
        "explanation": "Mercedes' hybrid-era dominance produced 8 straight Constructors' titles.",
        "category": "records", "difficulty": "easy",
    },
    {
        "question": "Which driver set a new record for most points scored in a single World Championship season in 2023?",
        "options": ["Lewis Hamilton", "Max Verstappen", "Sebastian Vettel", "Charles Leclerc"],
        "correct": 1,
        "explanation": "Verstappen's dominant 2023 campaign broke the single-season points record.",
        "category": "records", "difficulty": "medium",
    },
    {
        "question": "The 2016 title fight between Hamilton and Rosberg went all the way to which race before being decided?",
        "options": ["Brazilian GP", "Abu Dhabi GP", "United States GP", "Mexican GP"],
        "correct": 1,
        "explanation": "Rosberg secured the title by finishing second behind Hamilton at the Abu Dhabi season finale.",
        "category": "records", "difficulty": "medium",
    },
    {
        "question": "Before Max Verstappen's 10 straight wins in 2023, which driver held the record with 9 consecutive victories in a season?",
        "options": ["Michael Schumacher", "Sebastian Vettel", "Lewis Hamilton", "Nigel Mansell"],
        "correct": 1,
        "explanation": "Vettel's 2013 Red Bull won 9 races in a row before Verstappen surpassed it a decade later.",
        "category": "records", "difficulty": "medium",
    },

    # ---------------- DRIVERS (batch 3) ----------------
    {
        "question": "After leaving F1, Juan Pablo Montoya went on to have a successful career in which other racing series?",
        "options": ["NASCAR and IndyCar", "MotoGP", "World Rally Championship", "Formula E"],
        "correct": 0,
        "explanation": "Montoya became a race-winner in both IndyCar and NASCAR after his F1 career.",
        "category": "drivers", "difficulty": "medium",
    },
    {
        "question": "Rubens Barrichello was Michael Schumacher's Ferrari teammate for most of the 2000-2004 dominant era. Who preceded him as Schumacher's Ferrari teammate?",
        "options": ["Eddie Irvine", "Gerhard Berger", "Jean Alesi", "Nigel Mansell"],
        "correct": 0,
        "explanation": "Eddie Irvine partnered Schumacher from 1996-1999, finishing runner-up in the 1999 title race.",
        "category": "drivers", "difficulty": "hard",
    },
    {
        "question": "David Coulthard spent many seasons as teammate to which double World Champion at McLaren?",
        "options": ["Ayrton Senna", "Mika Hakkinen", "Alain Prost", "Kimi Raikkonen"],
        "correct": 1,
        "explanation": "Coulthard and Hakkinen were McLaren teammates through the late 1990s and into the 2000s.",
        "category": "drivers", "difficulty": "medium",
    },
    {
        "question": "Felipe Massa lost the 2008 World Championship by a single point, in dramatic fashion, to which driver?",
        "options": ["Fernando Alonso", "Lewis Hamilton", "Kimi Raikkonen", "Robert Kubica"],
        "correct": 1,
        "explanation": "Hamilton passed Timo Glock on the last corner of the last race to snatch the 2008 title from Massa.",
        "category": "drivers", "difficulty": "easy",
    },
    {
        "question": "Robert Kubica suffered a serious accident in 2011 in which discipline, sidelining him from F1 for years before a comeback?",
        "options": ["Rallying", "Karting", "Endurance racing", "Motocross"],
        "correct": 0,
        "explanation": "A rally crash in Italy in 2011 badly injured Kubica's arm, interrupting his F1 career for years.",
        "category": "drivers", "difficulty": "medium",
    },
    {
        "question": "Zhou Guanyu made history in 2022 as the first driver of which nationality to race in Formula 1?",
        "options": ["Chinese", "Indian", "Thai", "Vietnamese"],
        "correct": 0,
        "explanation": "Zhou Guanyu became F1's first Chinese driver, racing for Alfa Romeo from 2022.",
        "category": "drivers", "difficulty": "easy",
    },

    # ---------------- TEAMS (batch 3) ----------------
    {
        "question": "The Haas F1 Team, which entered the grid in 2016, is owned by which American businessman?",
        "options": ["Gene Haas", "Roger Penske", "Chip Ganassi", "Zak Brown"],
        "correct": 0,
        "explanation": "Gene Haas, also known for his NASCAR and machine tool businesses, founded the Haas F1 Team.",
        "category": "teams", "difficulty": "medium",
    },
    {
        "question": "Renault's works team has raced under which rebranded name since 2021?",
        "options": ["Alpine", "Lotus", "Renault Sport", "Ligier"],
        "correct": 0,
        "explanation": "The Renault works team was rebranded Alpine from the 2021 season onward.",
        "category": "teams", "difficulty": "easy",
    },
    {
        "question": "Williams Racing was founded by Frank Williams and which co-founder/technical partner?",
        "options": ["Patrick Head", "Adrian Newey", "Ross Brawn", "Gordon Murray"],
        "correct": 0,
        "explanation": "Frank Williams and engineer Patrick Head co-founded Williams Grand Prix Engineering in 1977.",
        "category": "teams", "difficulty": "hard",
    },
    {
        "question": "McLaren was founded in 1963 by a racing driver from which country?",
        "options": ["New Zealand", "Australia", "United Kingdom", "South Africa"],
        "correct": 0,
        "explanation": "Bruce McLaren, a New Zealander, founded the team that still bears his name.",
        "category": "teams", "difficulty": "medium",
    },
    {
        "question": "Red Bull Racing entered F1 in 2005 after purchasing which existing team?",
        "options": ["Jaguar Racing", "Arrows", "Stewart Grand Prix", "Benetton"],
        "correct": 0,
        "explanation": "Red Bull bought Ford's Jaguar Racing outfit in late 2004, rebranding it for the 2005 season.",
        "category": "teams", "difficulty": "medium",
    },
    {
        "question": "Mercedes returned to F1 as a full works constructor in 2010 by purchasing which reigning champion team?",
        "options": ["Brawn GP", "Honda Racing", "BAR", "Williams"],
        "correct": 0,
        "explanation": "Mercedes bought the championship-winning Brawn GP squad at the end of 2009.",
        "category": "teams", "difficulty": "medium",
    },

    # ---------------- RULES (batch 3) ----------------
    {
        "question": "Which aerodynamic concept, banned in the 1980s, was reintroduced to F1 car design in the major 2022 regulation overhaul?",
        "options": ["Ground effect", "Active suspension", "Turbo lag compensation", "Fan cars"],
        "correct": 0,
        "explanation": "The 2022 rules brought back ground-effect underfloor tunnels to generate downforce more efficiently.",
        "category": "rules", "difficulty": "hard",
    },
    {
        "question": "The 'halo' cockpit protection device was introduced to F1 in which season?",
        "options": ["2016", "2018", "2020", "2022"],
        "correct": 1,
        "explanation": "The halo became mandatory from the 2018 season to protect drivers' heads from debris and impacts.",
        "category": "rules", "difficulty": "medium",
    },
    {
        "question": "In a normal dry Grand Prix, drivers are required to use at least how many different tyre compounds during the race?",
        "options": ["One", "Two", "Three", "Four"],
        "correct": 1,
        "explanation": "F1 rules mandate using at least two of the available dry compounds during a dry race.",
        "category": "rules", "difficulty": "easy",
    },
    {
        "question": "Grid penalties can be applied to a driver for exceeding their allocation of which components across a season?",
        "options": ["Power unit elements", "Steering wheels", "Race suits", "Radio units"],
        "correct": 0,
        "explanation": "Using more power unit parts than allowed in a season results in grid position penalties.",
        "category": "rules", "difficulty": "medium",
    },
    {
        "question": "Which body is the international governing organization that makes and enforces F1's rules?",
        "options": ["FIA", "FOM", "FISA", "ACO"],
        "correct": 0,
        "explanation": "The Federation Internationale de l'Automobile (FIA) governs Formula 1's technical and sporting regulations.",
        "category": "rules", "difficulty": "easy",
    },
    {
        "question": "What is the purpose of the 'formation lap' driven just before the race start?",
        "options": [
            "To bring tyres and brakes up to temperature",
            "To determine the final grid order",
            "To let fans see the cars up close",
            "To test the pit lane speed limiter",
        ],
        "correct": 0,
        "explanation": "The formation lap warms up tyres and brakes before cars line up on the grid for the start.",
        "category": "rules", "difficulty": "easy",
    },

    # ---------------- MEME / ICONIC (batch 3) ----------------
    {
        "question": "Kimi Raikkonen's joyous \"Yes! Yes! Yes! Woohoo!\" radio message came after a rare late-career win at which 2018 race?",
        "options": ["United States GP", "Italian GP", "Monaco GP", "British GP"],
        "correct": 0,
        "explanation": "Raikkonen's win at the 2018 US GP, his first since 2013, produced one of his most memorable radio moments.",
        "category": "meme", "difficulty": "medium",
    },
    {
        "question": "Daniel Ricciardo popularized which unusual post-win celebration, drinking champagne out of his racing boot?",
        "options": ["The shoey", "The boot toast", "The victory chug", "The podium pour"],
        "correct": 0,
        "explanation": "Ricciardo's 'shoey' became one of the most recognizable celebrations in modern F1.",
        "category": "meme", "difficulty": "easy",
    },
    {
        "question": "Which race is remembered as the longest in F1 history, stretched out by a lengthy rain delay in 2011?",
        "options": ["Canadian GP", "Malaysian GP", "British GP", "Japanese GP"],
        "correct": 0,
        "explanation": "The 2011 Canadian GP took over 4 hours due to heavy rain interruptions, the longest race on record.",
        "category": "meme", "difficulty": "hard",
    },
    {
        "question": "\"Bono, my tyres are gone\" is a famous radio complaint from Lewis Hamilton to his race engineer, whose nickname is Bono. What is Bono's real name?",
        "options": ["Peter Bonnington", "Andrew Shovlin", "Riccardo Musconi", "Marcus Dudley"],
        "correct": 0,
        "explanation": "Peter 'Bono' Bonnington has been Hamilton's long-time race engineer at Mercedes.",
        "category": "meme", "difficulty": "hard",
    },
    {
        "question": "Sebastian Vettel's signature post-win celebration involved pointing which way?",
        "options": ["Skyward with one finger", "Both fists in the air", "Toward the crowd", "Toward his pit crew"],
        "correct": 0,
        "explanation": "Vettel's finger-to-the-sky gesture became one of his trademark victory celebrations.",
        "category": "meme", "difficulty": "medium",
    },
]


def total_questions() -> int:
    return len(QUESTIONS)


# --------------------------------------------------------------------------
# Want to add your own questions? Just append more dicts to QUESTIONS above,
# following the same format:
#
# QUESTIONS.append({
#     "question": "Your question here?",
#     "options": ["Option A", "Option B", "Option C", "Option D"],
#     "correct": 0,  # index of the right answer
#     "explanation": "Fun fact shown after the answer.",
#     "category": "meme",
#     "difficulty": "medium",  # easy=5pts, medium=10pts, hard=15pts
# })
# --------------------------------------------------------------------------
